### ISSUE TITLE
bandwidth_test with RDMC stops working after commit 9a57a9bd4fb4ab95fc9af07d6c892c153761823e

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#190]
@ZhengPeterWang found that the latest master does not work when he was evaluating with bandwidth_test (1MB message size 
, RDMC, 3 nodes, half sender), but the SMC works fine. I tested that and I can reproduce this with a different set of nodes. The phenomenon is that all nodes freeze after "Finished constructing/joining Group" message. I traced it back to commit 9a57a9bd4fb4ab95fc9af07d6c892c153761823e which introduced this issue because, in 5cfd35f1e7481d2e67bef5df40999c8171af5cc5, we dont have this issue.

@sagarjha, could you help to check this issue?

**Comment by KenBirman** [comment]
I bet the real issue is that we removed a barrier sync that was being done at the start of each new epoch, and when Sagar then changed these to be asynchronous (Edward recently made them puts with completion, hence they have a synchronous wait built in), the effect was that our epoch termination code lacked a needed sync to make sure the new view had been properly pushed to the participants.

I vote that we reinstall Edward’s changes, since they were tested and they do work.  Sagar felt they would be slow (the completion probably adds 50us of delay) but view changes are rare events, and the elimination of the barrier sync during the new epoch logic definitely will save a lot more than 50us!

We really need to fix our URL for running the unit tests when people check changes in.  This would have been caught, but because the tests did not run, Sagar didn’t notice!

**Comment by sagarjha** [comment]
Ken's theory seems plausible. I am going to take a look.

**Comment by sagarjha** [comment]
Tagging @ellerre 

I fixed the bug. Thanks to @ZhengPeterWang for finding it.

The bug had nothing to do with my reverting of Edward's changes (put vs. put_with_completion). The bug is not present in earlier commits, purely because it was introduced in the optimizations branch (`for_nsdi_opportunistic`) and merged to master recently. It has to do with how batched null sends are handled. 

Multiple nulls in continuation are sent in just one slot. The header of the message in that slot contains the number of nulls. This field was not set correctly - it was set after we received SMC messages in the hopes that during the receiving of SMC messages, zero or more nulls were issued which should be now aggregated. However, nulls can be issued naturally when receiving RDMC messages too, and in that case, this field was not getting set. The fix I implemented is moving the setting of the field to where we send the messages (null and otherwise) through SMC. This handles both execution paths, when we issue nulls in response to receiving RDMC messages and when we issue nulls in response to receiving SMC messages.

Lorenzo, you can confirm my bugfix, even though it's what Ken calls a "one-line fix".

**Comment by ellerre** [comment]
I confirm Sagar's analysis and bugfix. I introduced the bug with my latest branch merge. My fault, I'm sorry. Before merging I performed the basic tests, but only with small messages. Probably fixing the travis-ci automatic tests would had helped.

**Comment by songweijia** [comment]
Thank you @sagarjha for fix this. Btw. travis-ci does not do the test at all. it just test if the project builds. As we already have the regression test setup for a while, I again suggest that we should use that to test the major changes before we merge to master, which is exactly the purpose of the regression test kit.

**Comment by songweijia** [comment]
persistent_bw_test with SMC does not work with commit 9a57a9bd4fb4ab95fc9af07d6c892c153761823e. @sagarjha, let's have a meeting to check this together.

**Comment by KenBirman** [comment]
I still think 866a0e was correct and should not have been reverted!

**Comment by sagarjha** [comment]
@songweijia The problem was that null messages were also delivered to the application because Derecho thought they were 10KB in size. This meant that the application callback was called more times than it should have been, causing a mismatch in the version number expected of the final persisted message.

The issue was that now since null messages are not sent in the entire slot, but batched together, only the header of the first null is sent. But the size of a message in a slot appears towards the end of the slot. So the size is never sent. Derecho was still reading the size of a message from the end of the slot, even in the case of a null message. This size was about 10KB because of the previous message sent in the same slot. I fixed it by simply storing the size differently upon receipt; if a null message is received, its size is registered to be equal to the header size in the SMC receive handler. Lorenzo can confirm my changes.

This seems to have fixed the problem for me as persistent_bw_test now finishes successfully for two nodes. Feel free to reopen the issue if this doesn't work or if there are more bugs.

Lorenzo, I also recommend a thorough rerun of all the regression tests now just in case there are more bugs.

**Comment by sagarjha** [comment]
Actually, this is a problem that existed in the branch that was being evaluated for NSDI. I highly recommend we run the performance tests again. If null messages are delivered and counted as normal messages, we will see inflated performance numbers. That's dangerous!!!

**Comment by songweijia** [comment]
@ZhengPeterWang had done regression test and found that the latest change still does not fix the issue: presistent_bw_test with three node using SMC still get stuck nondeterministically. I tried with compute30-32 and it's very easy to reproduce that issue. Let's keep it open until regression test passed.

**Comment by sagarjha** [comment]
I see. I tested with two nodes and 100 messages. It was working all the time (after remove .plog before every test). I will try to reproduce the issue with three nodes.

**Comment by sagarjha** [comment]
Closing this again after I fixed another bug with how null messages are handled.

@ellerre It's dangerous to add incorrect information to `locally_stable_sst_messages` in the function `sst_receive_handler` when a node receives more than 1 nulls in a batch. For example, storing the `data` of the first null slot for subsequent slots was the cause of this bug that I fixed. As a simple fix, whether a message is a null message is now the FIRST check in the deliver message function. This is a hack but also entirely correct. But you should think about how to improve this situation and avoid any possible confusion. Also, since the headers of subsequent null slots are not going to be sent through RDMA, the `get_buffer_and_send_auto_null` function should also be optimized to not even bother filling up the header entries.

@ZhengPeterWang Can you test again and let us know if there are any more bugs?

**Comment by ZhengPeterWang** [comment]
The bug I raised has been fixed. I will start to do a reg test on the latest derecho ASAP.
